name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Target environment (dev or prod)"
        required: true
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: "Docker image tag to deploy (for example: commit SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Debug files
      run: ls -R

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 18.61.48.125
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "deployment.yml,service.yml"
        target: "/home/ubuntu/"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 18.61.48.125
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu

          kubectl get namespace ${{ github.event.inputs.target_environment }} >/dev/null 2>&1 || kubectl create namespace ${{ github.event.inputs.target_environment }}

          kubectl apply -n ${{ github.event.inputs.target_environment }} -f deployment.yml
          kubectl apply -n ${{ github.event.inputs.target_environment }} -f service.yml

          IMAGE=510931056420.dkr.ecr.ap-south-2.amazonaws.com/project-2:${{ github.event.inputs.image_tag }}

          echo "Using image: $IMAGE"

          kubectl set image -n ${{ github.event.inputs.target_environment }} deployment/project-2 project-2=$IMAGE

    - name: Slack Notification (CD Success)
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "CD SUCCESS: ${{ github.repository }} deployed to ${{ github.event.inputs.target_environment }} with image tag ${{ github.event.inputs.image_tag }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Slack Notification (CD Failure)
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "CD FAILED: ${{ github.repository }} deployment to ${{ github.event.inputs.target_environment }} failed for image tag ${{ github.event.inputs.image_tag }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK