name: CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint
      run: |
        pip install flake8
        flake8 .

    - name: Test
      run: |
        pip install pytest
        pytest || true

    - name: Install Snyk
      run: npm install -g snyk

    - name: Snyk Scan
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Configure AWS (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::510931056420:role/OIDC
        aws-region: ap-south-2

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 510931056420.dkr.ecr.ap-south-2.amazonaws.com

    - name: Build Image
      run: docker build -t project-2 .

    - name: Tag Image
      run: docker tag project-2:latest <ECR-URI>:${{ github.sha }}

    - name: Push Image
      run: docker push <ECR-URI>:${{ github.sha }}